### ISSUE TITLE
In the CIM, ValidateCustomerPaymentProfile should have the customerShippingAddressId as optional

### ISSUE THREAD

**Issue by gmarlett** [ajbdev/authorizenet-php-api#10]
In the CIM, ValidateCustomerPaymentProfile should have the customerShippingAddressId as optional.  If we do not use that, it should not be included in the SOAP request.

See:
http://community.developer.authorize.net/t5/Integration-and-Testing/CIM-SOAP-API-ValidateCustomerPaymentProfile-optional/td-p/2351

**Comment by ajbdev** [comment]
This repo isn't actively maintained. It was originally created simply to provide a composer package of the old authorize.net SDK. I'd recommend using the new official one here: https://github.com/AuthorizeNet/sdk-php
