### ISSUE TITLE
Invalid child element 'order'

### ISSUE THREAD

**Issue by MastermindsDigital** [ajbdev/authorizenet-php-api#11]
This error message only occurs from time to time and it not affecting all users/transaction. We are matching all requirements listed for SDK integration. This error message started last week...any advice?

Full error message:

Error: Error Message: The element 'profileTransAuthCapture' in namespace
'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'order'
in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible
elements expected: 'tax, shipping, duty, lineItems, customerProfileId' in
namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. E00003.

**Comment by deterset** [comment]
Having the same issue here. Don't have a clue how to fix this using their documentation. 
I removed <order></order> for now just so we could take orders.

It would be very nice to add this information though.

![screen shot 3-2](https://user-images.githubusercontent.com/1033513/27803304-d2ee5838-5ff6-11e7-84ac-8b51b8cb129e.PNG)

**Comment by ajbdev** [comment]
This repo isn't actively maintained. It was originally created simply to provide a composer package of the old authorize.net SDK. I'd recommend using the new official one here: https://github.com/AuthorizeNet/sdk-php
