### ISSUE TITLE
How to use cardCode ..?

### ISSUE THREAD

**Issue by waseemjutt** [ajbdev/authorizenet-php-api#13]
Hi,

there are only two fields  card_num and exp_date can you please help me how to add cardCode field i checked your all docs you'r not using cardCode field.

		$auth->card_num = '4111111111111111';
		$auth->exp_date = '04/18';

 but when i read authorized api doc there mention about cardCode. Please read

cardCode	The customer’s card code. 
The three- or four-digit number on the back of a credit card (on the front for American Express). 

This field is required if the merchant would like to use the Card Code Verification (CCV) security feature. 

Cardholder information must be stored securely and in accordance with the Payment Card Industry (PCI) Data Security Standard. 

For more information about PCI, please refer to the Standards, Compliance and Security developer training video at .

Regards.
Waseem Jutt

**Comment by ajbdev** [comment]
This repo isn't actively maintained. It was originally created simply to provide a composer package of the old authorize.net SDK. I'd recommend using the new official one here: https://github.com/AuthorizeNet/sdk-php
