### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by venkatcerulean** [ajbdev/authorizenet-php-api#14]
Below is my code
Where i am doing wrong
<?php
require_once 'AuthorizeNet.php';
define("AUTHORIZENET_API_LOGIN_ID", "xxxxxx");
define("AUTHORIZENET_TRANSACTION_KEY", "xxxxxxxx");
define("AUTHORIZENET_SANDBOX", true);
$request = new AuthorizeNetARB;
$response = $request->cancelSubscription($subscriptionId);
print_r($response);
?>
o/p : AuthorizeNetARB_Response Object ( [xml] => [response] => )

**Comment by ajbdev** [comment]
This repo isn't actively maintained. It was originally created simply to provide a composer package of the old authorize.net SDK. I'd recommend using the new official one here: https://github.com/AuthorizeNet/sdk-php
